# Generated by Django 2.0 on 2018-02-02 13:48

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_File',
            fields=[
                ('file_no', models.AutoField(primary_key=True, serialize=False)),
                ('file_title', models.TextField(default='')),
                ('file_path', models.FileField(blank=True, max_length=500, null=True, upload_to=posts.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='M_Post',
            fields=[
                ('post_no', models.AutoField(primary_key=True, serialize=False)),
                ('post_contents', models.TextField()),
                ('post_interests', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='M_Post_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.M_File')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.M_Post')),
            ],
        ),
    ]
