# Generated by Django 2.0 on 2018-01-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_pw', models.CharField(max_length=50)),
                ('user_gender', models.CharField(choices=[('M', 'M'), ('W', 'W')], default='M', max_length=1)),
                ('user_birthday', models.DateField(blank=True)),
                ('user_jdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
